// Remove server-side artefacts from dist/ before Capacitor copies it into the
// APK.
//
// `npm run build:native` writes BOTH the web bundle and the esbuild server
// bundle into dist/, because on the web host they are deployed together. But
// capacitor.config.ts has webDir: 'dist', so `cap sync` copies the whole
// directory into android/app/src/main/assets/public - and an .aab is just a
// zip. Without this step every shipped app carries:
//
//   dist/server.cjs      the compiled backend
//   dist/server.cjs.map  its sourcemap, which embeds sourcesContent - the
//                        complete original TypeScript of server.ts and every
//                        shared/ module, including the payment integration
//
// Verified: 144 KB of backend source was present in the first build.
//
// Only ever deletes from dist/, which is gitignored and regenerated by every
// build, so this can never eat tracked files.
import fs from 'fs';
import path from 'path';

const DIST = path.resolve(process.argv[2] || 'dist');

const REMOVE = [
  'server.cjs',
  'server.cjs.map',
];

if (!fs.existsSync(DIST)) {
  console.error(`prune-native-webdir: ${DIST} does not exist - run the build first.`);
  process.exit(1);
}

// Refuse to run anywhere that is not a build output directory, so a mistyped
// argument cannot delete from a source tree.
if (!fs.existsSync(path.join(DIST, 'index.html'))) {
  console.error(`prune-native-webdir: ${DIST} has no index.html - refusing to prune.`);
  process.exit(1);
}

let removed = 0;
for (const name of REMOVE) {
  const target = path.join(DIST, name);
  if (fs.existsSync(target)) {
    fs.rmSync(target, { force: true });
    console.log(`  removed ${name}`);
    removed++;
  }
}

// Any stray sourcemap is backend-shaped risk too; the web build does not emit
// them, so anything here is unexpected and worth failing loudly over.
const strays = fs.readdirSync(DIST).filter(f => f.endsWith('.map'));
if (strays.length) {
  console.error(`prune-native-webdir: unexpected sourcemaps left in dist/: ${strays.join(', ')}`);
  process.exit(1);
}

// The service worker MUST survive - deleting it silently breaks offline use.
if (!fs.existsSync(path.join(DIST, 'sw.js'))) {
  console.error('prune-native-webdir: sw.js is missing after pruning - the PWA service worker was lost.');
  process.exit(1);
}

console.log(`prune-native-webdir: ${removed} server artefact(s) removed, sw.js intact.`);
